/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pos;


import Login.SystemUser;
import customer.Customer;
import furniture.Furniture;
import gnu.io.SerialPort;
import java.io.OutputStream;
import java.math.BigDecimal;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import storeInfo.Company;






/**
 *
 * @author Ruoxi
 */
public class TransactionMember extends javax.swing.JFrame {

    private Main main = null;
    private SystemUser systemUser = null;
    private Company company = null;
    private List<Furniture> furnitureList = new ArrayList<>();
    private BigDecimal totalAmount = BigDecimal.ZERO;

    private String partnerPoleDisplayCOMPort = "COM4";
    private OutputStream partnerPoleDisplayOutputStream;
    SerialPort serialPort;

    private Customer customer = null;

    /**
     * Creates new form TransactionMember
     */
    public TransactionMember() {
        initComponents();
    }

    public TransactionMember(Main main, SystemUser sytemUser, Company company) {
        this();
        this.main = main;
        this.systemUser = sytemUser;
        this.company = company;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCustomerPhone = new javax.swing.JTextField();
        jButtonSearchCustomer = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabelCustomerName = new javax.swing.JLabel();
        jLabelDisplayPhone = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFurnitureList = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabelProductName = new javax.swing.JLabel();
        jTextFieldFurniturName = new javax.swing.JTextField();
        jLabelQuantity = new javax.swing.JLabel();
        jTextFieldQuantity = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabelTotalAmount = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabelUserCompany = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Island Furniture Point of Sale System");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Phone:");
        jLabel2.setToolTipText("");

        jTextFieldCustomerPhone.setToolTipText("");

        jButtonSearchCustomer.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonSearchCustomer.setText("Search");
        jButtonSearchCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchCustomerActionPerformed(evt);
            }
        });

        jLabelCustomerName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelCustomerName.setText("CustomerName");

        jLabelDisplayPhone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelDisplayPhone.setText("CustomerPhone");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCustomerName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelDisplayPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 21, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabelCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelDisplayPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTableFurnitureList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableFurnitureList);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add Product", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabelProductName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelProductName.setText("Product Name: ");

        jTextFieldFurniturName.setToolTipText("");
        jTextFieldFurniturName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFurniturNameActionPerformed(evt);
            }
        });

        jLabelQuantity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelQuantity.setText("Quantity:");

        jTextFieldQuantity.setToolTipText("");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1jButtonAddProductActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2jButtonClearActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("Close");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3jButtonCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jButton3)
                        .addGap(54, 54, 54))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelProductName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldFurniturName, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldFurniturName))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                        .addGap(35, 35, 35)
                        .addComponent(jButton1)))
                .addContainerGap())
        );

        jLabelTotalAmount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Total :");
        jLabel3.setToolTipText("");

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton4.setText("Payment");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4jButtonPaymentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jLabelTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jLabelUserCompany.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelUserCompany.setText("SystemUserName  and company info");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonSearchCustomer)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldCustomerPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(119, 119, 119)
                                .addComponent(jLabelUserCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 852, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldCustomerPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelUserCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSearchCustomer)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSearchCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchCustomerActionPerformed
        try {
            customer = getCustomerForPOS(jTextFieldCustomerPhone.getText());
            if (customer == null) {
                JOptionPane.showMessageDialog(this, "Cannot find customer", "Error", JOptionPane.ERROR_MESSAGE);
                jTextFieldCustomerPhone.setText("");
                jLabelCustomerName.setText("");
                jLabelDisplayPhone.setText("");

            } else {
                JOptionPane.showMessageDialog(this, "Customer data pulled successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
                jLabelCustomerName.setText("Customer Name: " + customer.getCustomerName());
                jLabelDisplayPhone.setText("Phone: " + customer.getPhone());
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "An unknown error has occurred: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonSearchCustomerActionPerformed

    private void jTextFieldFurniturNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFurniturNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFurniturNameActionPerformed

    private void jButton1jButtonAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1jButtonAddProductActionPerformed
        try {
            Furniture furniture = getFurnitureForPOS(jTextFieldFurniturName.getText());

            if (furniture == null) {
                JOptionPane.showMessageDialog(this, "No Such Product Sold in Store", "Error", JOptionPane.ERROR_MESSAGE);
                jTextFieldFurniturName.setText("");
                jTextFieldQuantity.setText("");

            } else {
                JOptionPane.showMessageDialog(this, "Product item added successfully", "Success", JOptionPane.INFORMATION_MESSAGE);

                //                byte[] clear = {0x0C};
                //                byte[] newLine = {0x0A};
                //                byte[] carriageReturn = {0x0D};
                //                byte[] message1 = furniture.getFurnitureName().getBytes();
                //                byte[] message2 = jTextFieldQuantity.getText().getBytes();
                //
                //                try {
                //                    partnerPoleDisplayOutputStream.write(clear);
                //                    partnerPoleDisplayOutputStream.write(message1);
                //                    partnerPoleDisplayOutputStream.write(newLine);
                //                    partnerPoleDisplayOutputStream.write(carriageReturn);
                //                    partnerPoleDisplayOutputStream.write(message2);
                //                } catch (IOException ex) {
                //                    JOptionPane.showMessageDialog(null, "Unable to write to Partner Pole Display: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                //                }
                furniture.setPOSquantity(Integer.parseInt(jTextFieldQuantity.getText()));
                jTextFieldFurniturName.setText("");
                jTextFieldQuantity.setText("");
                furnitureList.add(furniture);
                totalAmount = totalAmount.add(furniture.getPrice().multiply(new BigDecimal(furniture.getPOSquantity())));
                jLabelTotalAmount.setText(totalAmount.toString());
                loadTable();

            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "An unknown error has occurred: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1jButtonAddProductActionPerformed

    private void jButton2jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2jButtonClearActionPerformed
        jTextFieldFurniturName.setText("");
        jTextFieldQuantity.setText("");
        jLabelTotalAmount.setText("");
        jTextFieldCustomerPhone.setText("");
        jLabelCustomerName.setText("");
        jLabelDisplayPhone.setText("");
        customer = null;
        furnitureList.clear();
        resetTable();

    }//GEN-LAST:event_jButton2jButtonClearActionPerformed

    private void jButton3jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3jButtonCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3jButtonCloseActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        loadTable();

        if (systemUser != null) {
            jLabelUserCompany.setText("Login as " + systemUser.getUserName() + " at " + company.getCompanyName() + " in " + company.getCountry() + " " + company.getAddress());
        } else {
            jLabelUserCompany.setText("Please Login");
        }

        initPartnerPoleDisplay();
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        main.setVisible(true);

//         if(serialPort != null)
//        {
//            try
//            {
//                byte[] clear = {0x0C};
//                partnerPoleDisplayOutputStream.write(clear);
//                partnerPoleDisplayOutputStream.close();
//                serialPort.close();
//            }
//            catch(IOException ex)
//            {
//                ex.printStackTrace();
//            }
//        }
    }//GEN-LAST:event_formWindowClosed

    private void jButton4jButtonPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4jButtonPaymentActionPerformed
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
        Calendar cal = Calendar.getInstance();
        String date = dateFormat.format(cal.getTime());

        List<String> furnitureNameList = new ArrayList<>();
        List<Integer> amountList = new ArrayList<>();

        for (Furniture furniture : furnitureList) {
            furnitureNameList.add(furniture.getFurnitureName());
            amountList.add(furniture.getPOSquantity());
        }

        Random random = new Random();
        Integer value = random.nextInt(500000000);
        String transactionReference = value.toString();

        try {

              createTransationOrderforPOS(furnitureNameList, amountList, totalAmount, date, transactionReference);

//creat and transmit transaction order to HQ            
            String storeName = company.getCompanyName();
            createHQMemberTransationOrderforPOS(furnitureNameList, amountList, totalAmount, date, transactionReference, customer.getPhone(), storeName);

            JOptionPane.showMessageDialog(this, "Transaction Completed Successfully." + "Transaction Reference Number is :" + transactionReference, "Success", JOptionPane.INFORMATION_MESSAGE);

            ////write to pole display
//            byte[] clear = {0x0C};
//            byte[] newLine = {0x0A};
//            byte[] carriageReturn = {0x0D};
//            byte[] message0 = "Thank you for visitng Island Furniture".getBytes();
//            byte[] message1 = transactionReference.getBytes();
//            byte[] message2 = totalAmount.toString().getBytes();
//
//            try {
//                partnerPoleDisplayOutputStream.write(clear);
//                 partnerPoleDisplayOutputStream.write(message0);
//                partnerPoleDisplayOutputStream.write(message1);
//                partnerPoleDisplayOutputStream.write(newLine);
//                partnerPoleDisplayOutputStream.write(carriageReturn);
//                partnerPoleDisplayOutputStream.write(message2);
//            } catch (IOException ex) {
//                JOptionPane.showMessageDialog(null, "Unable to write to Partner Pole Display: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
//            }
//
////print receipt and cash box out
//            printerAndCashbox();
            
            
            jTextFieldFurniturName.setText("");
            jTextFieldQuantity.setText("");
            jLabelTotalAmount.setText("");
            jTextFieldCustomerPhone.setText("");
            jLabelCustomerName.setText("");
            jLabelDisplayPhone.setText("");
            customer = null;
            furnitureList.clear();
            resetTable();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "An unknown error has occurred: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton4jButtonPaymentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransactionMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransactionMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransactionMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransactionMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransactionMember().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonSearchCustomer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelCustomerName;
    private javax.swing.JLabel jLabelDisplayPhone;
    private javax.swing.JLabel jLabelProductName;
    private javax.swing.JLabel jLabelQuantity;
    private javax.swing.JLabel jLabelTotalAmount;
    private javax.swing.JLabel jLabelUserCompany;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableFurnitureList;
    private javax.swing.JTextField jTextFieldCustomerPhone;
    private javax.swing.JTextField jTextFieldFurniturName;
    private javax.swing.JTextField jTextFieldQuantity;
    // End of variables declaration//GEN-END:variables

    private void loadTable() {
        try {
            if (furnitureList != null && furnitureList.size() > 0) {
                Object[][] data = new Object[furnitureList.size()][6];

                for (int i = 0; i < furnitureList.size(); i++) {
                    Furniture furniture = furnitureList.get(i);
                    data[i][0] = furniture.getId();
                    data[i][1] = furniture.getFurnitureName();
                    data[i][2] = furniture.getCategory();
                    data[i][3] = furniture.getPrice();                
                    data[i][4] = furniture.getColor();
                    data[i][5] = furniture.getPOSquantity();
                }

                Object[] columnNames = new Object[6];
                columnNames[0] = "Product Item ID";
                columnNames[1] = "Name";
                columnNames[2] = "Category";
                columnNames[3] = "Price";             
                columnNames[4] = "Color";
                columnNames[5] = "Quantity";

                TableModel tableModel = new DefaultTableModel(data, columnNames);
                jTableFurnitureList.setModel(tableModel);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "An unknown error has occurred: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void resetTable() {
        try {
            DefaultTableModel model = (DefaultTableModel) jTableFurnitureList.getModel();
            model.setRowCount(0);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "An unknown error has occurred: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }

    private void initPartnerPoleDisplay() {
//        Enumeration commPortList = CommPortIdentifier.getPortIdentifiers();
//
//        while (commPortList.hasMoreElements()) {
//            CommPortIdentifier commPort = (CommPortIdentifier) commPortList.nextElement();
//
//            if (commPort.getPortType() == CommPortIdentifier.PORT_SERIAL
//                    && commPort.getName().equals(partnerPoleDisplayCOMPort)) {
//                try {
//                    serialPort = (SerialPort) commPort.open("UnifiedPointOfSale", 5000);
//                    partnerPoleDisplayOutputStream = serialPort.getOutputStream();
//                } catch (PortInUseException ex) {
//                    JOptionPane.showMessageDialog(null, "Unable to initialize Partner Pole Display: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
//                } catch (IOException ex) {
//                    JOptionPane.showMessageDialog(null, "Unable to initialize Partner Pole Display: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
//                }
//            }
//        }
    }

    
      private void printerAndCashbox() {
//        try {
//            Double margin = 1.0;
//            Integer lines = 8;
//            String test = null;
//
//            PrinterJob printerJob = PrinterJob.getPrinterJob();
//            PageFormat pageFormat = printerJob.defaultPage();
//            Paper paper = new Paper();
//            paper.setSize(180.0, (double) (paper.getHeight() + lines * 10.0));
//            paper.setImageableArea(margin, margin, paper.getWidth() - margin * 2, paper.getHeight() - margin * 2);
//            pageFormat.setPaper(paper);
//            pageFormat.setOrientation(PageFormat.PORTRAIT);
//
//            printerJob.setPrintable(jTableFurnitureList.getPrintable(JTable.PrintMode.NORMAL, null, null), pageFormat);
//
//            printerJob.print();
//        } catch (PrinterException ex) {
//            JOptionPane.showMessageDialog(null, "Unable to print to Partner Thermal Printer: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
//        }
    }
   
    


  


    private static Furniture getFurnitureForPOS(java.lang.String furnitureName) {
        furniture.FurnitureForPOS_Service service = new furniture.FurnitureForPOS_Service();
        furniture.FurnitureForPOS port = service.getFurnitureForPOSPort();
        return port.getFurnitureForPOS(furnitureName);
    }

 


    private static Customer getCustomerForPOS(java.lang.String phone) {
        customer.CustomerPOS_Service service = new customer.CustomerPOS_Service();
        customer.CustomerPOS port = service.getCustomerPOSPort();
        return port.getCustomerForPOS(phone);
    }

    private static void createTransationOrderforPOS(java.util.List<java.lang.String> furnitureNameList, java.util.List<java.lang.Integer> amountList, java.math.BigDecimal totalAmount, java.lang.String date, java.lang.String transactionReference) {
        storeTO.StoreTransactionOrder_Service service = new storeTO.StoreTransactionOrder_Service();
        storeTO.StoreTransactionOrder port = service.getStoreTransactionOrderPort();
        port.createTransationOrderforPOS(furnitureNameList, amountList, totalAmount, date, transactionReference);
    }

    private static void createHQMemberTransationOrderforPOS(java.util.List<java.lang.String> furnitureNameList, java.util.List<java.lang.Integer> amountList, java.math.BigDecimal totalAmount, java.lang.String date, java.lang.String transactionReference, java.lang.String customerPhone, java.lang.String storeName) {
        hqMemberTO.HQTransactionOrderMember_Service service = new hqMemberTO.HQTransactionOrderMember_Service();
        hqMemberTO.HQTransactionOrderMember port = service.getHQTransactionOrderMemberPort();
        port.createHQMemberTransationOrderforPOS(furnitureNameList, amountList, totalAmount, date, transactionReference, customerPhone, storeName);
    }

   
   

}
